### ISSUE TITLE
Hero Tags for Fabs and parent Fab UX

### ISSUE THREAD

**Issue by poppinjay13** [heshanka/2itemAnimatedFab#1]
All three floating action buttons have retained the default hero tags within the same subtree which might throw errors during navigation as such.
<pre><code>
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
Here is the subtree for one of the offending heroes: Hero
    tag: <default FloatingActionButton tag>
    state: _HeroState#45464
When the exception was thrown, this was the stack
#0      Hero._allHeroesFor.inviteHero.<anonymous closure>
package:flutter/…/widgets/heroes.dart:268
#1      Hero._allHeroesFor.inviteHero
package:flutter/…/widgets/heroes.dart:279
#2      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes.dart:298
#3      SingleChildRenderObjectElement.visitChildren
package:flutter/…/widgets/framework.dart:6105
#4      Hero._allHeroesFor.visitor

</code></pre>
It might be useful to specify distinct <code>heroTag:</code> values for each. Also a simple UX addition such as rotating or transforming the main fab from a <code>+</code> to a <code>x</code> when active might serve you well.

**Comment by heshanka** [comment]
Merged your fix.
